apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  completions: 3 # make it run 3 times, one after the other
  template:
    metadata:
      labels:
        run: busybox
    spec:
      restartPolicy: Never
      containers:
      - args:
        - /bin/sh
        - -c
        - echo hello;sleep 30;echo world
        image: busybox
        name: busybox
