apiVersion: v1
kind: Pod
metadata:
  name: pod-env
  labels:
    app: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: nginx
    ports:
      - containerPort: 80
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"