apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  volumes:
  - name: myvolume
    emptyDir: {}
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /my-volume
      name: myvolume