apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: pod-sec-ev
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom: 
    - secretRef: 
        name: anotherone # the name of the secret
