apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: gcr.io/[Project-Id]/hello:v1
    ports:
      - containerPort: 8080