apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: pod-ready
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
    readinessProbe: # declare the readiness probe
      httpGet: # Check using httpGet method
        path: / # Call localhost with root path
        port: 80 # Use port 80 for http call.
