apiVersion: v1
kind: Pod
metadata:
  labels:
    app: v1
  annotations:
    test: test-annotation
  name: my-nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80